import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
//import App from './App';
//import reportWebVitals from './reportWebVitals';
import CityWeather from './CityWeather';
import registerServiceWorker from './registerServiceWorker';
import './index.css';
import {shuffle, sample} from 'underscore';
import { BrowserRouter, Route, withRouter } from 'react-router-dom';
import AddACityForm from './AddCityForm';


const cities =  [
    {
        city: 'Miami',
        currentTemp: '100',
        lowTemp: '70',
        highTemp: '102',
        humidity: '48%',
        imageURL: '/file.jpg'
    },
    {
        city: 'San Diego',
        currentTemp: '68',
        lowTemp: '60',
        highTemp: '72',
        humidity: '10%',
        imageURL: '/file.jpg'
    },
    {
        city: 'Miami',
        currentTemp: '100',
        lowTemp: '70',
        highTemp: '102',
        humidity: '48%',
        imageURL: '/file.jpg'
    },
    {
        city: 'San Diego',
        currentTemp: '68',
        lowTemp: '60',
        highTemp: '72',
        humidity: '10%',
        imageURL: '/file.jpg'
    }
];

const state = {
    cityData: cities
};
// AUTOGENERATED
// ReactDOM.render(
//   <React.StrictMode>
//     <App />
//   </React.StrictMode>,
//   document.getElementById('root')
// );


function App(){
    return <CityWeather {...state}/>;
}

const CityWrapper = withRouter(({ history }) =>
  <AddACityForm onAddCity={(city) => {
    cities.push(city);
    history.push('/');
  }} />
);

function render(){
    ReactDOM.render(
        <BrowserRouter>
            <React.Fragment>
                <Route exact path="/" component={App} />
                <Route path="/add" component={CityWrapper} />
            </React.Fragment>
        </BrowserRouter>, document.getElementById('root')
        
    );
}

render();
registerServiceWorker();

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
//reportWebVitals();
