import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
//import App from './App';
//import reportWebVitals from './reportWebVitals';
import CityWeather from './CityWeather';
import registerServiceWorker from './registerServiceWorker';
import './index.css';

// AUTOGENERATED
// ReactDOM.render(
//   <React.StrictMode>
//     <App />
//   </React.StrictMode>,
//   document.getElementById('root')
// );

// ADDED BY STEVEN 7/1/2021
ReactDOM.render(<CityWeather/>, document.getElementById('root'));

registerServiceWorker();

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
//reportWebVitals();
